export default interface IOutputs{
    id?:number ,
    titre: string,
    classement: string,
    standard: string,
    livrable: string,
    validite: string,
    delai: string,
    cout_etude: string,
    frais_admin: string,
    penalite: string,
    ispayer: boolean,
    isenvironnement: boolean,
    isdate: boolean,
    periode?: any,
    frequence?: any,
    isrelation: boolean,
    ordre: number,
    created_at: Date,
    updated_at: Date,
}